import Head from 'next/head'
import ApplicationsTemplate from '../components/templates/ApplicationsTemplate/ApplicationsTemplate'

const Applications = (props: any) => {
  return (
    <>
      <Head>
        <title>Minhas aplicações</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ApplicationsTemplate {...props} />
      </main>
    </>
  )
}

export default Applications
