import { LoadingContext } from '@/contexts/LoadingContext'
import Head from 'next/head'
import { useContext, useEffect } from 'react'
import ApplicationsTemplate from '../components/templates/ApplicationsTemplate/ApplicationsTemplate'

const Applications = (props: any) => {
  const { setLoading } = useContext(LoadingContext)

  useEffect(() => {
    setLoading(false)
  }, [setLoading])

  return (
    <>
      <Head>
        <title>Minhas aplicações</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ApplicationsTemplate {...props} />
      </main>
    </>
  )
}

export default Applications
